services:
  mantel:
    build:
      context: .
      dockerfile: Dockerfile-dev-app
    ports:
      - 81:80
    volumes:
      - ./app:/var/www
      - ./app/public:/var/www/html
      - /var/www/bootstrap/cache 
      - /var/www/storage
    user: www-data
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    ports:
      - 5432:5432
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres 
      - POSTGRES_DB=db
    volumes:
      - ./docker-dev-volumes/pg_data:/var/lib/postgresql/data  # Persist PostgreSQL data